export type Country = { code: string; flag: string; name: string };

export const countries: Country[] = [
  { code: "+93", flag: "🇦🇫", name: "Afghanistan (افغانستان)" },
  { code: "+355", flag: "🇦🇱", name: "Albania (Shqipëri)" },
  { code: "+213", flag: "🇩🇿", name: "Algeria (الجزائر)" },
  { code: "+376", flag: "🇦🇩", name: "Andorra" },
  { code: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "+374", flag: "🇦🇲", name: "Armenia (Հայաստան)" },
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+43", flag: "🇦🇹", name: "Austria (Österreich)" },
  { code: "+994", flag: "🇦🇿", name: "Azerbaijan (Azərbaycan)" },
  { code: "+1", flag: "🇧🇸", name: "Bahamas" },
  { code: "+973", flag: "🇧🇭", name: "Bahrain (البحرين)" },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh (বাংলাদেশ)" },
  { code: "+375", flag: "🇧🇾", name: "Belarus (Беларусь)" },
  { code: "+32", flag: "🇧🇪", name: "Belgium (België)" },
  { code: "+501", flag: "🇧🇿", name: "Belize" },
  { code: "+229", flag: "🇧🇯", name: "Benin (Bénin)" },
  { code: "+591", flag: "🇧🇴", name: "Bolivia" },
  { code: "+387", flag: "🇧🇦", name: "Bosnia and Herzegovina (Босна и Херцеговина)" },
  { code: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "+55", flag: "🇧🇷", name: "Brazil (Brasil)" },
  { code: "+673", flag: "🇧🇳", name: "Brunei" },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria (България)" },
  { code: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "+257", flag: "🇧🇮", name: "Burundi (Uburundi)" },
  { code: "+855", flag: "🇰🇭", name: "Cambodia (កម្ពុជា)" },
  { code: "+237", flag: "🇨🇲", name: "Cameroon (Cameroun)" },
  { code: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "+238", flag: "🇨🇻", name: "Cape Verde (Kabu Verdi)" },
  { code: "+236", flag: "🇨🇫", name: "Central African Republic (République centrafricaine)" },
  { code: "+235", flag: "🇹🇩", name: "Chad (Tchad)" },
  { code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "+86", flag: "🇨🇳", name: "China (中国)" },
  { code: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "+269", flag: "🇰🇲", name: "Comoros (جزر القمر)" },
  { code: "+243", flag: "🇨🇩", name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)" },
  { code: "+242", flag: "🇨🇬", name: "Congo (Republic) (Congo-Brazzaville)" },
  { code: "+506", flag: "🇨🇷", name: "Costa Rica" },
  { code: "+225", flag: "🇨🇮", name: "Côte d'Ivoire" },
  { code: "+385", flag: "🇭🇷", name: "Croatia (Hrvatska)" },
  { code: "+53", flag: "🇨🇺", name: "Cuba" },
  { code: "+357", flag: "🇨🇾", name: "Cyprus (Κύπρος)" },
  { code: "+420", flag: "🇨🇿", name: "Czech Republic (Česká republika)" },
  { code: "+45", flag: "🇩🇰", name: "Denmark (Danmark)" },
  { code: "+253", flag: "🇩🇯", name: "Djibouti" },
  { code: "+593", flag: "🇪🇨", name: "Ecuador" },
  { code: "+20", flag: "🇪🇬", name: "Egypt (مصر)" },
  { code: "+503", flag: "🇸🇻", name: "El Salvador" },
  { code: "+240", flag: "🇬🇶", name: "Equatorial Guinea (Guinea Ecuatorial)" },
  { code: "+291", flag: "🇪🇷", name: "Eritrea" },
  { code: "+372", flag: "🇪🇪", name: "Estonia (Eesti)" },
  { code: "+251", flag: "🇪🇹", name: "Ethiopia" },
  { code: "+679", flag: "🇫🇯", name: "Fiji" },
  { code: "+358", flag: "🇫🇮", name: "Finland (Suomi)" },
  { code: "+33", flag: "🇫🇷", name: "France" },
  { code: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "+220", flag: "🇬🇲", name: "Gambia" },
  { code: "+995", flag: "🇬🇪", name: "Georgia (საქართველო)" },
  { code: "+49", flag: "🇩🇪", name: "Germany (Deutschland)" },
  { code: "+233", flag: "🇬🇭", name: "Ghana (Gaana)" },
  { code: "+30", flag: "🇬🇷", name: "Greece (Ελλάδα)" },
  { code: "+502", flag: "🇬🇹", name: "Guatemala" },
  { code: "+224", flag: "🇬🇳", name: "Guinea (Guinée)" },
  { code: "+245", flag: "🇬🇼", name: "Guinea-Bissau (Guiné Bissau)" },
  { code: "+592", flag: "🇬🇾", name: "Guyana" },
  { code: "+509", flag: "🇭🇹", name: "Haiti" },
  { code: "+504", flag: "🇭🇳", name: "Honduras" },
  { code: "+36", flag: "🇭🇺", name: "Hungary (Magyarország)" },
  { code: "+354", flag: "🇮🇸", name: "Iceland (Ísland)" },
  { code: "+91", flag: "🇮🇳", name: "India (भारत)" },
  { code: "+62", flag: "🇮🇩", name: "Indonesia" },
  { code: "+98", flag: "🇮🇷", name: "Iran (ایران)" },
  { code: "+964", flag: "🇮🇶", name: "Iraq (العراق)" },
  { code: "+353", flag: "🇮🇪", name: "Ireland" },
  { code: "+972", flag: "🇮🇱", name: "Israel (ישראל)" },
  { code: "+39", flag: "🇮🇹", name: "Italy (Italia)" },
  { code: "+81", flag: "🇯🇵", name: "Japan (日本)" },
  { code: "+962", flag: "🇯🇴", name: "Jordan (الأردن)" },
  { code: "+7", flag: "🇰🇿", name: "Kazakhstan (Казахстан)" },
  { code: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "+686", flag: "🇰🇮", name: "Kiribati" },
  { code: "+383", flag: "🇽🇰", name: "Kosovo" },
  { code: "+965", flag: "🇰🇼", name: "Kuwait (الكويت)" },
  { code: "+996", flag: "🇰🇬", name: "Kyrgyzstan (Кыргызстан)" },
  { code: "+856", flag: "🇱🇦", name: "Laos (ລາວ)" },
  { code: "+371", flag: "🇱🇻", name: "Latvia (Latvija)" },
  { code: "+961", flag: "🇱🇧", name: "Lebanon (لبنان)" },
  { code: "+266", flag: "🇱🇸", name: "Lesotho" },
  { code: "+231", flag: "🇱🇷", name: "Liberia" },
  { code: "+218", flag: "🇱🇾", name: "Libya (ليبيا)" },
  { code: "+423", flag: "🇱🇮", name: "Liechtenstein" },
  { code: "+370", flag: "🇱🇹", name: "Lithuania (Lietuva)" },
  { code: "+352", flag: "🇱🇺", name: "Luxembourg" },
  { code: "+389", flag: "🇲🇰", name: "Macedonia (Македонија)" },
  { code: "+261", flag: "🇲🇬", name: "Madagascar (Madagasikara)" },
  { code: "+265", flag: "🇲🇼", name: "Malawi" },
  { code: "+60", flag: "🇲🇾", name: "Malaysia" },
  { code: "+960", flag: "🇲🇻", name: "Maldives" },
  { code: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "+356", flag: "🇲🇹", name: "Malta" },
  { code: "+222", flag: "🇲🇷", name: "Mauritania (موريتانيا)" },
  { code: "+230", flag: "🇲🇺", name: "Mauritius (Moris)" },
  { code: "+52", flag: "🇲🇽", name: "Mexico (México)" },
  { code: "+691", flag: "🇫🇲", name: "Micronesia" },
  { code: "+373", flag: "🇲🇩", name: "Moldova (Republica Moldova)" },
  { code: "+377", flag: "🇲🇨", name: "Monaco" },
  { code: "+976", flag: "🇲🇳", name: "Mongolia (Монгол)" },
  { code: "+382", flag: "🇲🇪", name: "Montenegro (Crna Gora)" },
  { code: "+212", flag: "🇲🇦", name: "Morocco (المغرب)" },
  { code: "+258", flag: "🇲🇿", name: "Mozambique (Moçambique)" },
  { code: "+95", flag: "🇲🇲", name: "Myanmar (Burma) (မြန်မာ)" },
  { code: "+264", flag: "🇳🇦", name: "Namibia (Namibië)" },
  { code: "+674", flag: "🇳🇷", name: "Nauru" },
  { code: "+977", flag: "🇳🇵", name: "Nepal (नेपाल)" },
  { code: "+31", flag: "🇳🇱", name: "Netherlands (Nederland)" },
  { code: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "+505", flag: "🇳🇮", name: "Nicaragua" },
  { code: "+227", flag: "🇳🇪", name: "Niger (Nijar)" },
  { code: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "+850", flag: "🇰🇵", name: "North Korea (조선 민주주의 인민 공화국)" },
  { code: "+47", flag: "🇳🇴", name: "Norway (Norge)" },
  { code: "+968", flag: "🇴🇲", name: "Oman (عُمان)" },
  { code: "+92", flag: "🇵🇰", name: "Pakistan (پاکستان)" },
  { code: "+680", flag: "🇵🇼", name: "Palau" },
  { code: "+970", flag: "🇵🇸", name: "Palestine (فلسطين)" },
  { code: "+507", flag: "🇵🇦", name: "Panama (Panamá)" },
  { code: "+675", flag: "🇵🇬", name: "Papua New Guinea" },
  { code: "+595", flag: "🇵🇾", name: "Paraguay" },
  { code: "+51", flag: "🇵🇪", name: "Peru (Perú)" },
  { code: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "+48", flag: "🇵🇱", name: "Poland (Polska)" },
  { code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "+974", flag: "🇶🇦", name: "Qatar (قطر)" },
  { code: "+40", flag: "🇷🇴", name: "Romania (România)" },
  { code: "+7", flag: "🇷🇺", name: "Russia (Россия)" },
  { code: "+250", flag: "🇷🇼", name: "Rwanda" },
  { code: "+966", flag: "🇸🇦", name: "Saudi Arabia (المملكة العربية السعودية)" },
  { code: "+221", flag: "🇸🇳", name: "Senegal (Sénégal)" },
  { code: "+381", flag: "🇷🇸", name: "Serbia (Србија)" },
  { code: "+248", flag: "🇸🇨", name: "Seychelles" },
  { code: "+232", flag: "🇸🇱", name: "Sierra Leone" },
  { code: "+65", flag: "🇸🇬", name: "Singapore" },
  { code: "+421", flag: "🇸🇰", name: "Slovakia (Slovensko)" },
  { code: "+386", flag: "🇸🇮", name: "Slovenia (Slovenija)" },
  { code: "+252", flag: "🇸🇴", name: "Somalia (Soomaaliya)" },
  { code: "+27", flag: "🇿🇦", name: "South Africa" },
  { code: "+82", flag: "🇰🇷", name: "South Korea (대한민국)" },
  { code: "+211", flag: "🇸🇸", name: "South Sudan (جنوب السودان)" },
  { code: "+34", flag: "🇪🇸", name: "Spain (España)" },
  { code: "+94", flag: "🇱🇰", name: "Sri Lanka (ශ්\u200dරී ලංකාව)" },
  { code: "+249", flag: "🇸🇩", name: "Sudan (السودان)" },
  { code: "+597", flag: "🇸🇷", name: "Suriname" },
  { code: "+268", flag: "🇸🇿", name: "Swaziland" },
  { code: "+46", flag: "🇸🇪", name: "Sweden (Sverige)" },
  { code: "+41", flag: "🇨🇭", name: "Switzerland (Schweiz)" },
  { code: "+963", flag: "🇸🇾", name: "Syria (سوريا)" },
  { code: "+886", flag: "🇹🇼", name: "Taiwan (台灣)" },
  { code: "+992", flag: "🇹🇯", name: "Tajikistan" },
  { code: "+255", flag: "🇹🇿", name: "Tanzania" },
  { code: "+66", flag: "🇹🇭", name: "Thailand (ไทย)" },
  { code: "+670", flag: "🇹🇱", name: "Timor-Leste" },
  { code: "+228", flag: "🇹🇬", name: "Togo" },
  { code: "+676", flag: "🇹🇴", name: "Tonga" },
  { code: "+216", flag: "🇹🇳", name: "Tunisia (تونس)" },
  { code: "+90", flag: "🇹🇷", name: "Turkey (Türkiye)" },
  { code: "+993", flag: "🇹🇲", name: "Turkmenistan" },
  { code: "+256", flag: "🇺🇬", name: "Uganda" },
  { code: "+380", flag: "🇺🇦", name: "Ukraine (Україна)" },
  { code: "+971", flag: "🇦🇪", name: "United Arab Emirates (الإمارات العربية المتحدة)" },
  { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "+598", flag: "🇺🇾", name: "Uruguay" },
  { code: "+998", flag: "🇺🇿", name: "Uzbekistan (Oʻzbekiston)" },
  { code: "+678", flag: "🇻🇺", name: "Vanuatu" },
  { code: "+39", flag: "🇻🇦", name: "Vatican City (Città del Vaticano)" },
  { code: "+58", flag: "🇻🇪", name: "Venezuela" },
  { code: "+84", flag: "🇻🇳", name: "Vietnam (Việt Nam)" },
  { code: "+967", flag: "🇾🇪", name: "Yemen (اليمن)" },
  { code: "+260", flag: "🇿🇲", name: "Zambia" },
  { code: "+263", flag: "🇿🇼", name: "Zimbabwe" },
];

export const defaultCountry =
  countries.find((c) => c.name.startsWith("Brazil") || c.name.startsWith("Brasil")) ??
  countries[0]!;
