import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

async function requireAdm(supabase: any, userId: string) { const { data } = await supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle(); if (data?.role !== "adm") throw new Error("Somente o ADM pode configurar o Telegram Operacional."); }
const mask = (value?: string | null) => value ? `${value.slice(0, 6)}****${value.slice(-4)}` : null;

export const getTelegramOperationalIntegration = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await requireAdm(context.supabase, context.userId); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data } = await supabaseAdmin.from("telegram_operational_integrations" as any).select("bot_username,alert_chat_id,bot_token,status,last_error").maybeSingle(); return data ? { configured: data.status === "configured", saved: data.status !== "disabled", botUsername: data.bot_username, alertChatId: data.alert_chat_id, tokenMasked: mask(data.bot_token), status: data.status, lastError: data.last_error } : { configured: false, saved: false }; });

export const saveTelegramOperationalIntegration = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: unknown) => z.object({ botToken: z.string().trim().min(20), alertChatId: z.string().trim().regex(/^-?\d+$/, "Chat ID inválido.") }).parse(input)).handler(async ({ context, data }) => { await requireAdm(context.supabase, context.userId); const check = await fetch(`https://api.telegram.org/bot${data.botToken}/getMe`); const result = await check.json().catch(() => ({})); if (!check.ok || !result.ok) throw new Error("Token do bot inválido."); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data: existing } = await supabaseAdmin.from("telegram_operational_integrations" as any).select("id,webhook_secret").maybeSingle(); const secret = existing?.webhook_secret || crypto.randomUUID().replaceAll("-", ""); const webhookUrl = `${process.env["VITE_SITE_URL"] || "https://manostech-system.com.br"}/api/public/telegram-operational-webhook`; const hook = await fetch(`https://api.telegram.org/bot${data.botToken}/setWebhook`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: webhookUrl, secret_token: secret, allowed_updates: ["message"] }) }); const hookResult = await hook.json().catch(() => ({})); if (!hook.ok || !hookResult.ok) throw new Error(hookResult.description || "Não foi possível configurar o webhook do Telegram."); const payload = { bot_token: data.botToken, bot_username: result.result.username, alert_chat_id: data.alertChatId, webhook_secret: secret, status: "configured", last_error: null, updated_at: new Date().toISOString() }; const saved = existing ? await supabaseAdmin.from("telegram_operational_integrations" as any).update(payload).eq("id", existing.id) : await supabaseAdmin.from("telegram_operational_integrations" as any).insert(payload); if (saved.error) throw new Error(saved.error.message); return { success: true, botUsername: result.result.username }; });

export const testTelegramOperationalIntegration = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await requireAdm(context.supabase, context.userId); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { sendOperationalTelegramAlert } = await import("@/lib/telegram-operational.server"); const result = await sendOperationalTelegramAlert(supabaseAdmin, { title: "Teste do Gerente Operacional IA", description: "A integração com o Telegram está funcionando." }); if (!result.sent) throw new Error(result.message || "Telegram ainda não configurado."); return { success: true }; });

export const removeTelegramOperationalIntegration = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await requireAdm(context.supabase, context.userId); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data } = await supabaseAdmin.from("telegram_operational_integrations" as any).select("bot_token").maybeSingle(); if (data?.bot_token) await fetch(`https://api.telegram.org/bot${data.bot_token}/deleteWebhook`, { method: "POST" }); const { error } = await supabaseAdmin.from("telegram_operational_integrations" as any).delete().neq("id", "00000000-0000-0000-0000-000000000000"); if (error) throw new Error(error.message); return { success: true }; });
