/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated/campanhas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedFiliaisRouteImport } from './routes/_authenticated/filiais'
import { Route as AuthenticatedFinanceiroRouteRouteImport } from './routes/_authenticated/financeiro/route'
import { Route as AuthenticatedGerenteOperacionalRouteImport } from './routes/_authenticated/gerente-operacional'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedPortaisRouteImport } from './routes/_authenticated/portais'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRevendasRouteImport } from './routes/_authenticated/revendas'
import { Route as AuthenticatedVisitantesRouteImport } from './routes/_authenticated/visitantes'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/_authenticated/empresas.index'
import { Route as AuthenticatedEmpresasCompanyIdRouteImport } from './routes/_authenticated/empresas.$companyId'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro/index'
import { Route as AuthenticatedFinanceiroAReceberRouteImport } from './routes/_authenticated/financeiro/a-receber'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro/despesas'
import { Route as AuthenticatedFinanceiroEmAtrasoRouteImport } from './routes/_authenticated/financeiro/em-atraso'
import { Route as AuthenticatedFinanceiroFaturamentoRouteImport } from './routes/_authenticated/financeiro/faturamento'
import { Route as AuthenticatedMarketingCampaignIdRouteImport } from './routes/_authenticated/marketing.$campaignId'
import { Route as ApiPublicAsaasClientRouteImport } from './routes/api/public/asaas-client'
import { Route as ApiPublicAsaasManagerRouteImport } from './routes/api/public/asaas-manager'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ApiPublicAsaasWebhookV2RouteImport } from './routes/api/public/asaas-webhook-v2'
import { Route as ApiPublicOperationalJobRouteImport } from './routes/api/public/operational-job'
import { Route as AuthenticatedFinanceiroReciboChargeIdRouteImport } from './routes/_authenticated/financeiro/recibo.$chargeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFiliaisRoute = AuthenticatedFiliaisRouteImport.update({
  id: '/filiais',
  path: '/filiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRouteRoute =
  AuthenticatedFinanceiroRouteRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGerenteOperacionalRoute =
  AuthenticatedGerenteOperacionalRouteImport.update({
    id: '/gerente-operacional',
    path: '/gerente-operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortaisRoute = AuthenticatedPortaisRouteImport.update({
  id: '/portais',
  path: '/portais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevendasRoute = AuthenticatedRevendasRouteImport.update({
  id: '/revendas',
  path: '/revendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitantesRoute = AuthenticatedVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdRoute =
  AuthenticatedEmpresasCompanyIdRouteImport.update({
    id: '/empresas/$companyId',
    path: '/empresas/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroAReceberRoute =
  AuthenticatedFinanceiroAReceberRouteImport.update({
    id: '/a-receber',
    path: '/a-receber',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroEmAtrasoRoute =
  AuthenticatedFinanceiroEmAtrasoRouteImport.update({
    id: '/em-atraso',
    path: '/em-atraso',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroFaturamentoRoute =
  AuthenticatedFinanceiroFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedMarketingCampaignIdRoute =
  AuthenticatedMarketingCampaignIdRouteImport.update({
    id: '/marketing/$campaignId',
    path: '/marketing/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAsaasClientRoute = ApiPublicAsaasClientRouteImport.update({
  id: '/api/public/asaas-client',
  path: '/api/public/asaas-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasManagerRoute = ApiPublicAsaasManagerRouteImport.update({
  id: '/api/public/asaas-manager',
  path: '/api/public/asaas-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookV2Route = ApiPublicAsaasWebhookV2RouteImport.update({
  id: '/api/public/asaas-webhook-v2',
  path: '/api/public/asaas-webhook-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOperationalJobRoute = ApiPublicOperationalJobRouteImport.update({
  id: '/api/public/operational-job',
  path: '/api/public/operational-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinanceiroReciboChargeIdRoute =
  AuthenticatedFinanceiroReciboChargeIdRouteImport.update({
    id: '/recibo/$chargeId',
    path: '/recibo/$chargeId',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/filiais': typeof AuthenticatedFiliaisRoute
  '/gerente-operacional': typeof AuthenticatedGerenteOperacionalRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/portais': typeof AuthenticatedPortaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/revendas': typeof AuthenticatedRevendasRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/financeiro/a-receber': typeof AuthenticatedFinanceiroAReceberRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/em-atraso': typeof AuthenticatedFinanceiroEmAtrasoRoute
  '/financeiro/faturamento': typeof AuthenticatedFinanceiroFaturamentoRoute
  '/marketing/$campaignId': typeof AuthenticatedMarketingCampaignIdRoute
  '/api/public/asaas-client': typeof ApiPublicAsaasClientRoute
  '/api/public/asaas-manager': typeof ApiPublicAsaasManagerRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/asaas-webhook-v2': typeof ApiPublicAsaasWebhookV2Route
  '/api/public/operational-job': typeof ApiPublicOperationalJobRoute
  '/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/financeiro/recibo/$chargeId': typeof AuthenticatedFinanceiroReciboChargeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/filiais': typeof AuthenticatedFiliaisRoute
  '/gerente-operacional': typeof AuthenticatedGerenteOperacionalRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/portais': typeof AuthenticatedPortaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/revendas': typeof AuthenticatedRevendasRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/financeiro/a-receber': typeof AuthenticatedFinanceiroAReceberRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/em-atraso': typeof AuthenticatedFinanceiroEmAtrasoRoute
  '/financeiro/faturamento': typeof AuthenticatedFinanceiroFaturamentoRoute
  '/marketing/$campaignId': typeof AuthenticatedMarketingCampaignIdRoute
  '/api/public/asaas-client': typeof ApiPublicAsaasClientRoute
  '/api/public/asaas-manager': typeof ApiPublicAsaasManagerRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/asaas-webhook-v2': typeof ApiPublicAsaasWebhookV2Route
  '/api/public/operational-job': typeof ApiPublicOperationalJobRoute
  '/empresas': typeof AuthenticatedEmpresasIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/financeiro/recibo/$chargeId': typeof AuthenticatedFinanceiroReciboChargeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/filiais': typeof AuthenticatedFiliaisRoute
  '/_authenticated/gerente-operacional': typeof AuthenticatedGerenteOperacionalRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/portais': typeof AuthenticatedPortaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/revendas': typeof AuthenticatedRevendasRoute
  '/_authenticated/visitantes': typeof AuthenticatedVisitantesRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/_authenticated/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/_authenticated/financeiro/a-receber': typeof AuthenticatedFinanceiroAReceberRoute
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/financeiro/em-atraso': typeof AuthenticatedFinanceiroEmAtrasoRoute
  '/_authenticated/financeiro/faturamento': typeof AuthenticatedFinanceiroFaturamentoRoute
  '/_authenticated/marketing/$campaignId': typeof AuthenticatedMarketingCampaignIdRoute
  '/api/public/asaas-client': typeof ApiPublicAsaasClientRoute
  '/api/public/asaas-manager': typeof ApiPublicAsaasManagerRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/asaas-webhook-v2': typeof ApiPublicAsaasWebhookV2Route
  '/api/public/operational-job': typeof ApiPublicOperationalJobRoute
  '/_authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/financeiro/recibo/$chargeId': typeof AuthenticatedFinanceiroReciboChargeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/financeiro'
    | '/assinatura'
    | '/campanhas'
    | '/configuracoes'
    | '/creditos'
    | '/dashboard'
    | '/eventos'
    | '/filiais'
    | '/gerente-operacional'
    | '/mensagens'
    | '/portais'
    | '/relatorios'
    | '/revendas'
    | '/visitantes'
    | '/portal/$slug'
    | '/empresas/$companyId'
    | '/financeiro/a-receber'
    | '/financeiro/despesas'
    | '/financeiro/em-atraso'
    | '/financeiro/faturamento'
    | '/marketing/$campaignId'
    | '/api/public/asaas-client'
    | '/api/public/asaas-manager'
    | '/api/public/asaas-webhook'
    | '/api/public/asaas-webhook-v2'
    | '/api/public/operational-job'
    | '/empresas/'
    | '/financeiro/'
    | '/financeiro/recibo/$chargeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assinatura'
    | '/campanhas'
    | '/configuracoes'
    | '/creditos'
    | '/dashboard'
    | '/eventos'
    | '/filiais'
    | '/gerente-operacional'
    | '/mensagens'
    | '/portais'
    | '/relatorios'
    | '/revendas'
    | '/visitantes'
    | '/portal/$slug'
    | '/empresas/$companyId'
    | '/financeiro/a-receber'
    | '/financeiro/despesas'
    | '/financeiro/em-atraso'
    | '/financeiro/faturamento'
    | '/marketing/$campaignId'
    | '/api/public/asaas-client'
    | '/api/public/asaas-manager'
    | '/api/public/asaas-webhook'
    | '/api/public/asaas-webhook-v2'
    | '/api/public/operational-job'
    | '/empresas'
    | '/financeiro'
    | '/financeiro/recibo/$chargeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/financeiro'
    | '/_authenticated/assinatura'
    | '/_authenticated/campanhas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/creditos'
    | '/_authenticated/dashboard'
    | '/_authenticated/eventos'
    | '/_authenticated/filiais'
    | '/_authenticated/gerente-operacional'
    | '/_authenticated/mensagens'
    | '/_authenticated/portais'
    | '/_authenticated/relatorios'
    | '/_authenticated/revendas'
    | '/_authenticated/visitantes'
    | '/portal/$slug'
    | '/_authenticated/empresas/$companyId'
    | '/_authenticated/financeiro/a-receber'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/financeiro/em-atraso'
    | '/_authenticated/financeiro/faturamento'
    | '/_authenticated/marketing/$campaignId'
    | '/api/public/asaas-client'
    | '/api/public/asaas-manager'
    | '/api/public/asaas-webhook'
    | '/api/public/asaas-webhook-v2'
    | '/api/public/operational-job'
    | '/_authenticated/empresas/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/financeiro/recibo/$chargeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ApiPublicAsaasClientRoute: typeof ApiPublicAsaasClientRoute
  ApiPublicAsaasManagerRoute: typeof ApiPublicAsaasManagerRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicAsaasWebhookV2Route: typeof ApiPublicAsaasWebhookV2Route
  ApiPublicOperationalJobRoute: typeof ApiPublicOperationalJobRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filiais': {
      id: '/_authenticated/filiais'
      path: '/filiais'
      fullPath: '/filiais'
      preLoaderRoute: typeof AuthenticatedFiliaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerente-operacional': {
      id: '/_authenticated/gerente-operacional'
      path: '/gerente-operacional'
      fullPath: '/gerente-operacional'
      preLoaderRoute: typeof AuthenticatedGerenteOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portais': {
      id: '/_authenticated/portais'
      path: '/portais'
      fullPath: '/portais'
      preLoaderRoute: typeof AuthenticatedPortaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revendas': {
      id: '/_authenticated/revendas'
      path: '/revendas'
      fullPath: '/revendas'
      preLoaderRoute: typeof AuthenticatedRevendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitantes': {
      id: '/_authenticated/visitantes'
      path: '/visitantes'
      fullPath: '/visitantes'
      preLoaderRoute: typeof AuthenticatedVisitantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas/': {
      id: '/_authenticated/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/$companyId': {
      id: '/_authenticated/empresas/$companyId'
      path: '/empresas/$companyId'
      fullPath: '/empresas/$companyId'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/a-receber': {
      id: '/_authenticated/financeiro/a-receber'
      path: '/a-receber'
      fullPath: '/financeiro/a-receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroAReceberRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/em-atraso': {
      id: '/_authenticated/financeiro/em-atraso'
      path: '/em-atraso'
      fullPath: '/financeiro/em-atraso'
      preLoaderRoute: typeof AuthenticatedFinanceiroEmAtrasoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/faturamento': {
      id: '/_authenticated/financeiro/faturamento'
      path: '/faturamento'
      fullPath: '/financeiro/faturamento'
      preLoaderRoute: typeof AuthenticatedFinanceiroFaturamentoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/marketing/$campaignId': {
      id: '/_authenticated/marketing/$campaignId'
      path: '/marketing/$campaignId'
      fullPath: '/marketing/$campaignId'
      preLoaderRoute: typeof AuthenticatedMarketingCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/asaas-client': {
      id: '/api/public/asaas-client'
      path: '/api/public/asaas-client'
      fullPath: '/api/public/asaas-client'
      preLoaderRoute: typeof ApiPublicAsaasClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-manager': {
      id: '/api/public/asaas-manager'
      path: '/api/public/asaas-manager'
      fullPath: '/api/public/asaas-manager'
      preLoaderRoute: typeof ApiPublicAsaasManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook-v2': {
      id: '/api/public/asaas-webhook-v2'
      path: '/api/public/asaas-webhook-v2'
      fullPath: '/api/public/asaas-webhook-v2'
      preLoaderRoute: typeof ApiPublicAsaasWebhookV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/operational-job': {
      id: '/api/public/operational-job'
      path: '/api/public/operational-job'
      fullPath: '/api/public/operational-job'
      preLoaderRoute: typeof ApiPublicOperationalJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financeiro/recibo/$chargeId': {
      id: '/_authenticated/financeiro/recibo/$chargeId'
      path: '/recibo/$chargeId'
      fullPath: '/financeiro/recibo/$chargeId'
      preLoaderRoute: typeof AuthenticatedFinanceiroReciboChargeIdRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
  }
}

interface AuthenticatedFinanceiroRouteRouteChildren {
  AuthenticatedFinanceiroAReceberRoute: typeof AuthenticatedFinanceiroAReceberRoute
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFinanceiroEmAtrasoRoute: typeof AuthenticatedFinanceiroEmAtrasoRoute
  AuthenticatedFinanceiroFaturamentoRoute: typeof AuthenticatedFinanceiroFaturamentoRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
  AuthenticatedFinanceiroReciboChargeIdRoute: typeof AuthenticatedFinanceiroReciboChargeIdRoute
}

const AuthenticatedFinanceiroRouteRouteChildren: AuthenticatedFinanceiroRouteRouteChildren =
  {
    AuthenticatedFinanceiroAReceberRoute: AuthenticatedFinanceiroAReceberRoute,
    AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
    AuthenticatedFinanceiroEmAtrasoRoute: AuthenticatedFinanceiroEmAtrasoRoute,
    AuthenticatedFinanceiroFaturamentoRoute:
      AuthenticatedFinanceiroFaturamentoRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
    AuthenticatedFinanceiroReciboChargeIdRoute:
      AuthenticatedFinanceiroReciboChargeIdRoute,
  }

const AuthenticatedFinanceiroRouteRouteWithChildren =
  AuthenticatedFinanceiroRouteRoute._addFileChildren(
    AuthenticatedFinanceiroRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFinanceiroRouteRoute: typeof AuthenticatedFinanceiroRouteRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFiliaisRoute: typeof AuthenticatedFiliaisRoute
  AuthenticatedGerenteOperacionalRoute: typeof AuthenticatedGerenteOperacionalRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPortaisRoute: typeof AuthenticatedPortaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRevendasRoute: typeof AuthenticatedRevendasRoute
  AuthenticatedVisitantesRoute: typeof AuthenticatedVisitantesRoute
  AuthenticatedEmpresasCompanyIdRoute: typeof AuthenticatedEmpresasCompanyIdRoute
  AuthenticatedMarketingCampaignIdRoute: typeof AuthenticatedMarketingCampaignIdRoute
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFinanceiroRouteRoute:
    AuthenticatedFinanceiroRouteRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFiliaisRoute: AuthenticatedFiliaisRoute,
  AuthenticatedGerenteOperacionalRoute: AuthenticatedGerenteOperacionalRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPortaisRoute: AuthenticatedPortaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRevendasRoute: AuthenticatedRevendasRoute,
  AuthenticatedVisitantesRoute: AuthenticatedVisitantesRoute,
  AuthenticatedEmpresasCompanyIdRoute: AuthenticatedEmpresasCompanyIdRoute,
  AuthenticatedMarketingCampaignIdRoute: AuthenticatedMarketingCampaignIdRoute,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalSlugRoute: PortalSlugRoute,
  ApiPublicAsaasClientRoute: ApiPublicAsaasClientRoute,
  ApiPublicAsaasManagerRoute: ApiPublicAsaasManagerRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicAsaasWebhookV2Route: ApiPublicAsaasWebhookV2Route,
  ApiPublicOperationalJobRoute: ApiPublicOperationalJobRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
